export const TYPE_EVENT = "EVENT";
export const TYPE_MOTION = "MOTION";

export const SUBTYPE_EVENT_FLAG = "FLAG";
export const SUBTYPE_EVENT_SPRITE = "SPRITE";

export const SUBTYPE_MOTION_LINEAR = "LINEAR";
export const SUBTYPE_MOTION_ROTATE_ANTICLOCKWISE = "ANTICLOCKWISE";
export const SUBTYPE_MOTION_ROTATE_CLOCKWISE = "CLOCKWISE";


export const NEW_GROUP = "NEW GROUP";
export const START_GROUP = "START GROUP";
export const END_GROUP = "END GROUP";